spring.application.name=bank_api_gateway

server.port = 8888

eureka.client.serviceUrl.defaultZone=http://localhost:8761/registery/eureka

# Enable dynamic routing 
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# To convert url to lowercase
spring.cloud.gateway.discovery.locator.lower-case-service-id=true